import { MODEL_INFO } from '@/features/Models/Types';

export default [
  {
    id: 'qwen2_5_0_5b_q4',
    name: 'Qwen2.5 0.5B Instruct',
    description:
      'Ultra lightweight multilingual model for mobile testing and basic translation.',
    recommended: true,
    sizeBytes: 390000000,
    ramRequirementGB: 1,
    parameters: '0.5B',
    quantization: 'Q4_K_M',
    contextLength: 4096,
    languages: [
      'English',
      'Hindi',
      'Spanish',
      'French',
      'German',
      'Arabic',
      'Chinese',
    ],
    capabilities: ['translation', 'chat', 'summarization', 'markdown'],
    mobilePerformance: 'excellent',
    quality: 'basic',
    downloadUrl:
      'https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct-GGUF/resolve/main/qwen2.5-0.5b-instruct-q4_k_m.gguf',
    fileName: 'qwen2.5-0.5b-instruct-q4_k_m.gguf',
  },
  {
    id: 'qwen2_5_1_5b_q4',
    name: 'Qwen2.5 1.5B Instruct',
    description: 'Best balance between quality and mobile performance.',
    recommended: true,
    sizeBytes: 1200000000,
    ramRequirementGB: 3,
    parameters: '1.5B',
    quantization: 'Q4_K_M',
    contextLength: 8192,
    languages: [
      'English',
      'Hindi',
      'Spanish',
      'French',
      'German',
      'Arabic',
      'Chinese',
      'Japanese',
    ],
    capabilities: [
      'translation',
      'chat',
      'reasoning',
      'summarization',
      'markdown',
    ],
    mobilePerformance: 'good',
    quality: 'high',
    downloadUrl:
      'https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct-GGUF/resolve/main/qwen2.5-1.5b-instruct-q4_k_m.gguf',
    fileName: 'qwen2.5-1.5b-instruct-q4_k_m.gguf',
  },
  {
    id: 'tinyllama_1_1b_q4',
    name: 'TinyLlama 1.1B Chat',
    description: 'Very fast lightweight model for testing inference pipelines.',
    recommended: false,
    sizeBytes: 700000000,
    ramRequirementGB: 2,
    parameters: '1.1B',
    quantization: 'Q4_K_M',
    contextLength: 2048,
    languages: ['English'],
    capabilities: ['chat', 'testing', 'streaming'],
    mobilePerformance: 'excellent',
    quality: 'medium',
    downloadUrl:
      'https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF/resolve/main/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf',
    fileName: 'tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf',
  },
  {
    id: 'gemma_2b_q4',
    name: 'Gemma 2B Instruct',
    description:
      'Higher quality small model with good multilingual understanding.',
    recommended: true,
    sizeBytes: 1700000000,
    ramRequirementGB: 4,
    parameters: '2B',
    quantization: 'Q4_K_M',
    contextLength: 8192,
    languages: ['English', 'Hindi', 'French', 'German', 'Spanish'],
    capabilities: ['translation', 'reasoning', 'summarization'],
    mobilePerformance: 'medium',
    quality: 'high',
    downloadUrl:
      'https://huggingface.co/bartowski/gemma-2-2b-it-GGUF/resolve/main/gemma-2-2b-it-Q4_K_M.gguf',
    fileName: 'gemma-2-2b-it-Q4_K_M.gguf',
  },
  {
    id: 'qwen2_5_3b_q4',
    name: 'Qwen2.5 3B Instruct',
    description:
      'Production-grade multilingual model for advanced translation quality.',
    recommended: true,
    sizeBytes: 2500000000,
    ramRequirementGB: 6,
    parameters: '3B',
    quantization: 'Q4_K_M',
    contextLength: 16384,
    languages: [
      'English',
      'Hindi',
      'Spanish',
      'French',
      'German',
      'Arabic',
      'Chinese',
      'Japanese',
      'Korean',
    ],
    capabilities: [
      'translation',
      'reasoning',
      'summarization',
      'markdown',
      'structured-output',
    ],
    mobilePerformance: 'medium',
    quality: 'very-high',
    downloadUrl:
      'https://huggingface.co/Qwen/Qwen2.5-3B-Instruct-GGUF/resolve/main/qwen2.5-3b-instruct-q4_k_m.gguf',
    fileName: 'qwen2.5-3b-instruct-q4_k_m.gguf',
  },
] as const satisfies Array<MODEL_INFO>;
